api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
#
#    enable_fos_user: true
#    swagger:
#        api_keys:
#            apiKey:
#                name: Authorization
#                type: header

