#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#authentication_token:
#  path: /authentication_token
#  controller: FormLoginBundle:Login:login
#  methods: ['POST']

register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST

authentication_token:
  path: /authentication_token
  methods: ['POST']

#event_post:
#  path: /api/events
#  methods: POST
#  controller: App\Controller\EventController::post